### ISSUE TITLE
[FEATURE] record with start_beep: true is unsupported

### ISSUE THREAD

**Issue by ik5** [adhearsion/ruby_fs#3]
When using `record` with freeswitch, there is an exception that `start_beep: true` is not supported, but without it, there is no uri method, and it renders the `record` method invalid.

**Comment by benlangfeld** [comment]
Please re-file this against Punchblock, where the issue resides. Also note
that your assertion about a link between start_beep and the recording URI
is false.

Regards,
Ben Langfeld
